angular.module('collectionModule',['ui.router'])
.config(function($stateProvider){
	$stateProvider
	.state('bookrack.collection',{
		url:'/collection',
		templateUrl:'all/bookrack/collection/collection.html',
		css:'all/bookrack/collection/collection.css',
		controller:'collectionCtrl'
	})
})
.controller('collectionCtrl',['$scope',function($scope){
	//给所有的checkbox设置点击事件
	$scope.checkStatus = function(obj){
		if($(obj.target).hasClass('checked')){
			$(obj.target).removeClass('checked');
		}else{
			$(obj.target).addClass('checked');
		}
	}
}])
